# Generated by Django 3.0.5 on 2020-09-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=5, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('water_line_compaitable', models.BooleanField(default=False)),
                ('model', models.CharField(default='', max_length=10)),
                ('pack_size', models.IntegerField(default=0)),
                ('flavor', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
